cc_binary(
    name = "main",
    srcs = ["main.cpp", "color.hpp", "vec3.hpp", "ray.hpp", "hittable.hpp", "sphere.hpp", "utility.hpp", "hittable_list.hpp", "interval.hpp", "camera.hpp", "material.hpp", "aabb.hpp", "bvh.hpp", "texture.hpp", "rtw_stb_image.hpp", "perlin.hpp", "quad.hpp", "constant_medium.hpp", "external/stb_image.h"],
    data = ["texturemaps/earthmap.jpg"]
)
